mozilla/addons-blog

- bin/build-script
- eleventy.config.js
- libs/templates.js
- package.json
- yarn.lock
fixes https://github.com/mozilla/addons-blog/issues/3
> Use DOMPurify

- .circleci/config.yml
- README.md
- package.json
> Add circle-ci config

- .circleci/config.yml
- .prettierignore
- .prettierrc
- package.json
- Use default `proseWrap` setting used in other projects
- Prettify markdown files
- Run prettier on CI
> Update prettier config

- .circleci/config.yml
- package.json
- src/assets/css/inc/prev-next-nav.scss
> Use stylelint

- eleventy.config.js
- package.json
- src/filters.js
- tests/filters.test.js
- tests/fixtures/testproject/src/content/escaped.njk
- tests/fixtures/testproject/src/content/unescaped.njk
- tests/integration.test.js
> Add tests for sanitization/dompurify 

- README.md
- package.json
- src/wordpress.js
fixes https://github.com/mozilla/addons-blog/issues/40
> Add `start:nocache` command

- src/content/blog.njk
- src/content/blogposts.njk
- src/wordpress.js
- tests/fixtures/apiPost.js
- tests/wordpress.test.js
> Fix post data and rewrite internal URLs

- .circleci/config.yml
- .gitignore
- .prettierignore
- composer.json
- composer.lock
- package.json
- phpunit.xml.dist
- src/wp-content/blogposts.njk
- tests/php/WordPressThemeTest.php
- tests/php/bootstrap.php
- tests/php/fake-template-functions.php
- yarn.lock
Fixes #53 
---
It's not ultra pretty but it works.
> Add some PHPUnit tests for the WP theme

- renovate.json
We want to use the same strategy for all dev dependencies.
> Update renovate config for PHP

- eleventy.config.js
- tests/php/WordPressThemeTest.php
We don't need the robots.txt in the WP theme I think.
> Do not copy robots.txt in WP theme

- .gitignore
- README.md
- eleventy.config.js
- package.json
This is needed to use `mozAddonManager` locally, which will be needed for the install button.
> Add start:https command

- eleventy.config.js
- package.json
- src/content/feed.njk
- src/data/markup.js
- src/filters.js
- src/layouts/base.njk
- src/wp-content/blogposts.njk
- src/wp-content/index.njk
- tests/filters.test.js
- tests/php/WordPressThemeTest.php
- yarn.lock
Fixes #16
---
This is an Atom feed and not "RSS" but I think it should be pretty much the same?
> Add Atom feed

- README.md
- bin/build-script
- bin/build-styles
- src/wordpress.js
- tests/wordpress.test.js
- add some docs about our env vars
- add new env vars to have more control and allow deployments on pretty much any hosting platform
- add some tests
> Add new env variables to easily deploy the blog

- src/assets/css/blogposts.scss
- src/content/blogposts.njk
- src/includes/blogpost.njk
- src/wp-content/blogposts.njk
This will make things a bit easier in the future as most of the HTML will be located in one place, and it should help keep everything up to date.
> Use shared template (include) for single blogpost page

- src/content/blog.njk
- src/content/blogposts.njk
- src/includes/blog-entry.njk
- src/includes/blogpost.njk
- src/wp-content/blog.njk
- src/wp-content/blogposts.njk
- tests/php/fake-template-functions.php
Fixes #90
I also fixed a problem in the WP theme where the wrong date was used.
> Fixes for the created/modified dates

- package.json
We shouldn't rewrite urls in local dev to be able to display the images, etc.
> Don't rewrite urls in local dev

- src/assets/css/blogposts.scss
- src/assets/css/header.scss
- src/assets/css/inc/prev-next-nav.scss
- src/assets/css/inc/variables.scss
- src/content/blogposts.njk
- src/includes/blogpost.njk
- src/wp-content/blogposts.njk
- tests/php/fake-template-functions.php
Fixes https://github.com/mozilla/addons-blog/issues/94
also fixes https://github.com/mozilla/addons-blog/issues/73
---
See:
- https://addons-blog-preview.vercel.app/blog/2021/03/24/blog-post-lorem-ipsum-001/
- https://addons-blog-preview.vercel.app/blog/2021/03/31/safer-and-stronger-passwords-with-lastpass/
> Update dimensions to be more consistent with the latest mocks

- src/assets/css/blogposts.scss
> Add style for pull-quote

- src/wp-content/blogposts.njk
- tests/php/fake-template-functions.php
Fixes https://github.com/mozilla/addons-blog/issues/103
---
I think I didn't spot this issue before because my local WP instance probably
has a user with ID = 1 and I was looking at the first post...
> Fix avatar in WP theme

- src/wordpress.js
> Do not fetch data when building the WP theme

- src/assets/css/header.scss
Fixes https://github.com/mozilla/addons-blog/issues/111
> Fix feature image in Safari

- src/wordpress.js
- tests/wordpress.test.js
Fixes https://github.com/mozilla/addons-blog/issues/119
---
See: https://addons-blog-preview-willdurand.vercel.app/blog/2021/03/24/blog-post-lorem-ipsum-001/
> Do not rewrite /wp-content/ urls

- package.json
- src/content/404.md
- src/content/blog.njk
- src/content/index.njk
- src/data/markup.js
- src/layouts/base.njk
- src/wp-content/blog.njk
- tests/data/markup.test.js
- tests/php/WordPressThemeTest.php
- yarn.lock
Fixes https://github.com/mozilla/addons-blog/issues/107
----
This depends on: https://github.com/mozilla/addons-frontend/pull/10380, and I left a note in this PR because the "More..." dropdown is very ugly for some reasons so I removed it. I'll add it later, probably (although it's quite convenient to only have 3 links on small screens).
Deployed at: https://addons-blog-preview-willdurand.vercel.app/blog/
> Replace header for list of blogposts page

- bin/deploy.sh
This file will get removed by the later "aws s3 sync --delete" command if it is
located in the previous "dist" directory.
> Save __version__ file to "dist/blog"

- src/assets/js/dynamic-addon-cards.js
- tests/assets/dynamic-addon-cards.test.js
Fixes https://github.com/mozilla/addons-blog/issues/140
---
Please read the issue to get some more information (hopefully). Given that this code is executed on the client, one could see the button being changed on the fly **but** the header is taking most of the page so that cannot happen (under normal circumstances). Anyway, let's make it work first, and we'll see if it needs some polish later.
This code is quite similar to what we have for addons-frontend.
Firefox for iOS:
Firefox:
Non-Firefox is on -dev already.
> Convert button in StaticAddonCard to an install button when UserAgent is Firefox

- package.json
- yarn.lock
`0.10.0` updates the links in the header.
> Update addons-frontend-blog-utils to 0.10.0

- bin/build-script
- package.json
- src/assets/js/setup-dropdown-menu.js
- tests/assets/setup-dropdown-menu.test.js
- yarn.lock
Fixes https://github.com/mozilla/addons-blog/issues/153
> Add dropdown menu on small header

- src/assets/js/dynamic-addon-cards.js
- tests/assets/dynamic-addon-cards.test.js
Fixes #143 
---
It's a bit "bare bone" but it is functional. You can use `yarn start:https` to try this patch with `mozAddonManager` available, see: https://github.com/mozilla/addons-blog#yarn-starthttps
> Install add-on with mozAddonManager

- src/includes/blogpost.njk
- tests/php/WordPressThemeTest.php
see: https://github.com/mozilla/addons-blog/issues/72#issuecomment-822774586
> Update UTM params for Twitter

- src/assets/css/blogposts.scss
- src/assets/css/inc/variables.scss
- src/content/blogposts.njk
- src/includes/blogpost.njk
- src/wp-content/blogposts.njk
- tests/php/WordPressThemeTest.php
> Add breadcrumbs

- bin/build-script
- package.json
- src/assets/js/dynamic-addon-cards.js
- tests/assets/dynamic-addon-cards.test.js
- yarn.lock
> Add compatibility checks (min version)

- src/assets/css/blog.scss
- src/includes/blog-entry.njk
> Add link around image and title

- src/assets/css/styles.scss
- src/assets/js/setup-dropdown-menu.js
- tests/assets/setup-dropdown-menu.test.js
Fixes https://github.com/mozilla/addons-blog/issues/157
> Open 'More...' menu on hover

- src/assets/js/dynamic-addon-cards.js
- tests/assets/dynamic-addon-cards.test.js
Fixes https://github.com/mozilla/addons-blog/issues/186
Fixes https://github.com/mozilla/addons-blog/issues/187
> Update install button for themes and disable it on Fenix

- bin/deploy.sh
- eleventy.config.js
- src/content/404.md
> Set an error.html page to handle 404s

- eleventy.config.js
- src/content/feed.njk
- src/nunjucks.js
- tests/content/feed.test.js
Fixes https://github.com/mozilla/addons-blog/issues/192
---
Not sure how we can have a test for that.. See: #159
> Add safe filter to content in Atom feed

- src/includes/blogpost.njk
- tests/php/WordPressThemeTest.php
Fixes https://github.com/mozilla/addons-blog/issues/217
> Use siteTitle in breadcrumb

- package.json
- src/assets/js/dynamic-addon-cards.js
- tests/assets/dynamic-addon-cards.test.js
- yarn.lock
fixes https://github.com/mozilla/addons-blog/issues/224
> Update dependency addons-frontend-blog-utils to ^0.20.0

- .circleci/config.yml
Fixes https://github.com/mozilla/addons-blog/issues/2
> Add config to deploy to prod

- .circleci/config.yml
Fixes https://github.com/mozilla/addons-blog/issues/264
---
This patch is needed to keep consistency across all our projects.
> Use Node 14

- src/assets/js/dynamic-addon-cards.js
Fixes https://github.com/mozilla/addons-blog/issues/301
---
Obviously I could have done that in #297 but I thought it would be more involved than that (sorry, it was late).
> Remove `current_version.file` check

- package.json
- yarn.lock
I got fed up with waiting for renovate to create a PR
> Update addons-frontend-blog-utils to v0.27.0

- src/data/markup.js
- tests/php/WordPressThemeTest.php
> Change the name of the blog

- src/filters.js
- tests/filters.test.js
> Relax the regex for addonId to allow any character

- .circleci/config.yml
- .gitignore
- eleventy.config.js
- src/assets/js/dynamic-addon-cards.js
- src/data/markup.js
- src/filters.js
- src/layouts/base.njk
- src/wordpress.js
- tests/assets/dynamic-addon-cards.test.js
- tests/filters.test.js
- tests/php/WordPressThemeTest.php
- tests/wordpress.test.js
~~Depends on https://github.com/mozilla/addons-blog/pull/343~~
Fixes #308
> Allow blog to use APIs from different environments

- .circleci/config.yml
> Pass the correct value for AMO_BASE_URL to build-blog-dev

- tests/integration-production.test.js
> Fix the integration test

- src/assets/js/setup-dropdown-menu.js
- tests/assets/setup-dropdown-menu.test.js
Backport of https://github.com/mozilla/addons-frontend/issues/11137 since addons-blog has its own custom (simplified) client-side implementation of the dropdown.
Fixes #369
> Workaround for the Dropdown double-tap issue on mobile

- .circleci/config.yml
> switch deprecated circleci/ docker images to cimg/

- package.json
- tests/assets/analytics.test.js
- tests/assets/dynamic-addon-cards.test.js
- tests/assets/setup-dropdown-menu.test.js
- yarn.lock
Closes https://github.com/mozilla/addons-blog/pull/377
---
It makes sense to verify the "web" bundle and not just the "node" bundle so I think this config is more accurate.
> Update addons-frontend-blog-utils to 0.33.0 and fix jest config

- README.md
I am not sure if we need more than that. I will submit a PR on addons-frontend, too (related to this one).
> Add some more information about the WordPress theme in the README

- src/content/blog.njk
- src/content/blogposts.njk
- src/content/feed.njk
> Consider post title safe - it's rendered by wordpress

- .circleci/config.yml
> Use Node 16

- bin/deploy.sh
Fixes mozilla/addons-frontend#398
> Use the dev URLs for connect-src and img-src

- bin/build-styles
- src/assets/css/styles.scss
- tests/integration-production.test.js
> Fix import of addons-frontend-blog-utils css

- src/assets/js/dynamic-addon-cards.js
- tests/assets/dynamic-addon-cards.test.js
Fixes https://github.com/mozilla/addons-blog/issues/568
> Allow all add-ons compatible with Android to be installed

- README.md
- eleventy.config.js
Fixes https://github.com/mozilla/addons-blog/issues/573
> Configure eleventy dev server to serve content over HTTPS

- bin/deploy.sh
- src/assets/js/analytics.js
- tests/assets/analytics.test.js
https://mozilla-hub.atlassian.net/browse/AMO-95
> Add GA4 support to analytics (with UA in parallel)

- .circleci/config.yml
- package.json
https://bugzilla.mozilla.org/show_bug.cgi?id=1940383
See also https://github.com/mozilla/addons-frontend/pull/13396
> Don't specify a package name or version, this package is not published
