mozilla/addons-blog

.circleci/config.yml
eleventy.config.js

Fixes https://github.com/mozilla/addons-blog/issues/41
---
After #22, building the WP theme removes the PHP code that is used to output the template directory URIs. This patch fixes it and adds a test to avoid regressions in the future.

Do not override safe fiter when building the WP theme

---

eleventy.config.js
src/content/blog.njk
src/content/index.njk
src/data/markup.js
src/filters.js
src/includes/head.njk
tests/filters.test.js

fixes https://github.com/mozilla/addons-blog/issues/10
---

Render Yoast tags in blog posts

---

src/wp-content/blogposts.njk

This has been introduced by mistake after the last PR merged, because we
switched from the use of a layout to extending the base layout...

Fix WP single page

---

.gitignore
src/wp-content/functions.njk
tests/php/WordPressThemeTest.php

refs #8 
---
In order to be able to set featured images, we need to tell WP that the theme
supports featured images.

Enable support for post thumbnails in WP theme

---

src/assets/css/header.scss
src/assets/css/styles.scss
src/layouts/base.njk
tests/php/WordPressThemeTest.php

fixes #71 
---
So.. I fixed the header to have something very close to the current mocks. I know we'd like to avoid inline styles, but I don't really know how to do that with an image tag. See: https://github.com/mozilla/addons-blog/issues/79 for that particular problem.
Super large screen:
Mobile:

Refactor header a bit

---

src/assets/css/blogpost-nav.scss
src/assets/css/blogposts.scss
src/assets/css/styles.scss
src/content/blogposts.njk
src/includes/blogpost-nav-next.njk
src/includes/blogpost-nav-prev.njk
src/wp-content/blogposts.njk
tests/php/fake-template-functions.php

This patch introduces shared templates for the blogpost (bottom) nav. Class
names have been updated for consistency and the nav is now present in the WP
theme.
I updated the WP theme on the moz instance so you can have a look at how it looks.

Refactor blogpost nav (fix minor UI glitch, make it work in WP)

---

src/assets/css/styles.scss

This fixes an issue with long strings. See: https://addons-blog-preview-willdurand.vercel.app/blog/2021/04/13/ipsumipsumipsumipsumipsumipsumipsumipsumipsumipsum-ipsumipsumipsumipsum/
After:

Add overflow-wrap: anywhere

---

README.md
bin/asset-pipeline
bin/build-script
bin/build-styles
eleventy.config.js
src/layouts/base.njk
src/wp-content/blogposts.njk
tests/assets-pipeline.test.js
tests/php/WordPressThemeTest.php

This is needed to be able to deploy the blog correctly (see #83), which essentially means pushing the content of `dist/blog/` instead of `dist/`, which contains unwanted files (like 404, fake index page, etc.). The changes are backward-compatible:
- the WP theme works as before but contains a `blog/assets/` dir instead of `assets/` (not a big deal)
- the local dev (`yarn start`) is exactly as before
- the production build works, too (asset pipeline OK)

Move assets/ to blog/

---

src/assets/css/styles.scss

Fixes https://github.com/mozilla/addons-blog/issues/108

Add overflow-wrap: break-word for Safari

---

.circleci/config.yml
bin/build-version-json.sh
bin/deploy.sh
package.json

A few notes about this PR:
1. This PR mimics how we deploy https://github.com/mozilla/extension-workshop.
2. The `deploy.sh` script assumes that all built assets are located in `dist/` directory. If this is incorrect, then we can adjust that.
3. The files that `deploy.sh` script tries to upload may need change too.
4. The CSP and other headers in `deploy.sh` may need to be adjusted to suit the need of this project.
5. This PR only deals with deploying -dev environment. If we were to follow the example of extension-workshop project, we would need to use the tags to give a hint as to which env we want to deploy, e.g. `v1.0.0-stage` is deployed to -stage and `v1.0.0` is deployed to -prod. See [[1]](https://github.com/mozilla/extension-workshop/blob/d04c3d4ca9f687de45a5bf3a05e3217bb4d7d306/.ci …

Deploy blog on -dev

---

src/assets/css/blog.scss
src/assets/css/blogposts.scss
src/assets/css/header.scss
src/assets/css/inc/variables.scss
src/assets/css/styles.scss

Fixes https://github.com/mozilla/addons-blog/issues/132
Fixes https://github.com/mozilla/addons-blog/issues/133
I also made sure that it would look good on small/medium screens.
---
("before" screenshots in the issue)
After:

Fix header on small screens, update some style (UX feedback)

---

bin/asset-pipeline
bin/build-script
src/assets/js/dynamic-addon-cards.js
tests/assets/dynamic-addon-cards.test.js
tests/fixtures/amo-api-response-tabby.json

refs #52 
Fixes https://github.com/mozilla/addons-blog/issues/134
---
This is the starting point of the client js we need for the blog, with tests. The only "feature" right now is to change the style of the card when the add-on is no longer available.
For the testing part, I tried to come up with a small abstraction layer to write test cases in an expressive manner. It's using the code that we use at build time to generate static cards that will be modified later by the script added in this PR. In addition to not have to write and maintain too much HTML in the tests, it will allow us to potentially catch issues if the `blog-utils` library is updated.
Once this lands, we'll be able to iterate on this script to add new features such as compatibility checks, mozAddonManager support, etc.

Add dynamic-addon-cards script

---

bin/build-script
package.json
src/assets/js/dynamic-addon-cards.js
tests/assets/dynamic-addon-cards.test.js
yarn.lock

Fixes https://github.com/mozilla/addons-blog/issues/138
---
This is needed for compatibility checks and so on in the future. I made this small patch to require `ua-parser-js` and update the tests. It will be less code to review in the next patch that will bring the compatibility checks.

Use `UAParser` to set the correct `app` in the API call

---

bin/deploy.sh

It was accidentally removed in https://github.com/mozilla/addons-blog/pull/130.

Add back the missing --delete option

---

.circleci/config.yml
bin/build-version-json.sh

Fixes #148 (hopefully)
---
1. The secrets for -stage are already configured so it should work
2. I tried the build/deploy stage (without pushing to S3) in https://app.circleci.com/pipelines/github/mozilla/addons-blog/377/workflows/381b5f3b-b273-4b7f-b827-9e31c493a574
3. I don't know if the cron task is going to work, it looks like we will only know once the PR lands
4. I added a `buildtime` field in the `version.json` file because it's convenient

Deploy to -stage

---

bin/build-script
package.json
src/assets/css/blog.scss
src/assets/css/blogpost-nav.scss
src/assets/css/blogposts.scss
src/assets/css/header.scss
yarn.lock

Fixes https://github.com/mozilla/addons-blog/issues/167
---
Only the "More..." link isn't fixed because it seems to be an addons-frontend issue.
I tested on Chrome and Firefox with the pref `accessibility.tabfocus` set to `7`.
Something we could improve later (maybe) is: at the bottom of a blog post, we go up to the Twitter share button before going to the navigation links.

Fix focus styles for keyboard navigation

---

src/assets/css/styles.scss

Fixes https://github.com/mozilla/addons-blog/issues/176
---
Sorry for the back and forth. This seems to work as we expect now, on all browsers.

Use 'word-break: break-word' instead of 'overflow-wrap: anywhere'

---

src/wordpress.js
tests/wordpress.test.js

Fixes #218 
---
We'll need to update a setting in WP: Settings > Permalinks > (select) Post name

Remove date in permalinks

---

eleventy.config.js
src/content/404.njk
src/content/blogposts.njk
src/content/feed.njk
src/content/index.njk
src/content/sitemap.njk
src/filters.js
tests/content/sitemap.test.js
tests/filters.test.js

Fixes #204 
---
This should generate the following file and content:
```
$ cat build/blog/sitemap.xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
<url>
<loc>https://addons.mozilla.org/blog/</loc>
<lastmod>2021-04-15</lastmod>
</url>
<url>
<loc>https://addons.mozilla.org/blog/the-best-adblockers-for-firefox-2/</loc>
<lastmod>2021-06-14</lastmod>
</url>
<url>
<loc>https://addons.mozilla.org/blog/best-adblockers-firefox-2021/</loc>
<lastmod>2021-06-11</lastmod>
</url>
</urlset>
```

Generate sitemap.xml

---

src/assets/css/blogposts.scss

Fixes #236 
Fixes https://github.com/mozilla/addons-blog/issues/242
---
Before:
After:

Update style a bit (for the launch)

---

src/assets/css/blogposts.scss

Remove underline from headers that are also links

---

src/assets/css/header.scss

Fixes #262
---
Editorial uses rather long titles so we need to reduce the font-size a bit on small-ish screens to avoid the titles to be "cut" (= hidden behind the actual content). ~~I haven't found an easy way to adjust the font size automatically (e.g., depending on the screen height), in part because the "header" is already dynamically adjusted according to the screen height. This change looks good on most screens so I think we're good.~~ => Switched to `vh`
Note: this isn't reproducible on all small screens but that's a problem on my mobile device.
Before:
After:

Fix title size on small-ish screens

---

README.md

Fixes https://github.com/mozilla/addons-blog/issues/269
---
This PR updates the README to explain how we currently use git tags and Circle CI to deploy this blog. Everyone should be able to deploy it given that this strategy does not require ops or special access that members of our team don't already have.
There is also a section about the WordPress theme, which isn't particularly important these days.

Add some notes about deployment

---

bin/deploy.sh

Fixes #270
---
This is needed because feed/sitemap XML files aren't hashed.

Configure short cache for XML files

---

bin/build-version-json.sh

Fixes #277
---
We use `$AMO_BASE_URL` to determine the environment because it is already set in the Circle configuration. The command to read the tag is almost always the same, only the pattern is different (for -prod, it looks like git will choose the shortest tag, which is why we don't need to exclude the `-stage` suffix but we'll see...). For -dev, the tag is now empty, which is what we seem to do for addons-frontend (and that kinda makes sense).

Set the right tag in version.json

---

src/assets/js/analytics.js
tests/assets/analytics.test.js

Fixes https://mozilla-hub.atlassian.net/browse/AMO-95

Fix GA4 dataLayer function - can't use rest params

---

.circleci/config.yml

Note: This is for the build step. The deployment step runs on `cimg/python:3.11-node` which should already be using Node 18.x
Fixes #603

Bump Node.js to 18.x
